Add support of allowed-failures

diff --git a/daemon/get_gdm.in b/daemon/get_gdm.in
--- a/daemon/get_gdm.in
+++ b/daemon/get_gdm.in
@@ -50,4 +50,6 @@ gsettings get org.gnome.desktop.interface clock-show-seconds >> /tmp/GET_GDM
 else
 gsettings get org.gnome.shell.clock show-seconds >> /tmp/GET_GDM
 fi
+echo -n "ALLOWED_FAILURES=" >> /tmp/GET_GDM 
+gsettings get org.gnome.login-screen allowed-failures >> /tmp/GET_GDM || echo >> /tmp/GET_GDM
 echo "EOF" >> /tmp/GET_GDM
